### ISSUE TITLE
Port to null safety

### ISSUE THREAD

**Issue by raphael-bmec-co** [mohammedX6/poly_bool_dart#1]
Hi

Do you have any intension of porting this to nullsafety?

**Comment by mohammedX6** [comment]
Hi and welcome,
Porting this library to Null Saftey is tricky from my perspective because I don't know how internals works, I think the best I can do is to just enforce all classes to use the old Dart version (2.11), But you will face annoying warnings about versioning. [Read more here](https://dart.dev/null-safety/unsound-null-safety)
In the meanwhile, I will release a new version with unsound null safety compatibility.

**Comment by mohammedX6** [comment]
A new version is ready you can try it out.

**Comment by raphael-bmec-co** [comment]
@mohammedX6 awesome. Thank you we will give it a shot.

**Comment by ignatz** [comment]
Hi Mohammed,

just flagging this since dart3 is around the corner, which will strictly require sound null safety.

> Null Saftey is tricky from my perspective because I don't know how internals works

Could you elaborate? If you don't know how the code works, is this a straightforward conversion of polybooljs? Maybe on a tangent, I was wondering what your confidence is around others using this library. For example, I noticed that there are no tests (there's a test that doesn't assert anything) and was wondering what your thoughts are? Cheers!

**Comment by mohammedX6** [comment]
@ignatz Hi!

There is a Fork for Null safety but I didn't test it, Please try it , If it's working as it should be i will merge it directly .

In our company we are using this library in our production apps, We conducted many extreme test cases and all runs good.

**Comment by mohammedX6** [comment]
Here is the link for the fork

https://github.com/BMEC/poly_bool_dart

**Comment by ignatz** [comment]
I looked at the fork and it seems like a pretty naive minimal conversion sprinkling some "?" and "!". It shouldn't change the behavior, at the end of the day it's just type annotations. The code semantically isn't particularly null-safe, where previously you might have accessed a null unchecked, there's now a "!". The behavior is unchanged.  Work would still be needed to lift the behavioral requirements into the API contract to achieve actual null-safety. Arguably, the places where unchecked accesses can occur is more obvious now, which is a slight improvement (at least in theory, not in production).

> We conducted many extreme test cases and all runs good.

Would you mind committing those to the repo as well? This would make it a lot easier to build confidence and confidently evolve the code base.

**Comment by mohammedX6** [comment]
Our tests was based on real data from out GIS server, I can't share them, my recommendation is to try to use the tests in the polybooljs library.

For null safety fork, it's should work for Dart 3.0 ?

**Comment by ignatz** [comment]
> For null safety fork, it's should work for Dart 3.0 ?

From a language point-of-view the patch is fine, i.e. it would run under dart 3.0. It's just not null-safe in the traditional sense. Specifically,there are a lot of nullable types that are being accessed unchecked. In practice, the library might just throw some null exceptions at you or seemingly valid input.

For visibility, I took the path and tried to see how far I could take it: https://github.com/ignatz/poly_bool_dart (I also added some simple tests and removed some of the egregious dependencies). I still wouldn't call it null-safe (thought the number of unchecked accesses to nullable types is certainly down). Some of my changes were more invasive, which is is working-as-intended on one hand, on the other I'm not super confident I didn't accidentally introduce bugs (that's why the tests).

**Comment by mohammedX6** [comment]
hi sorry for late replay, can i merge it to main repo ? 
If you want why not make a pull request

**Comment by ignatz** [comment]
Happy to send a PR. Just to be clear. I did quite a few invasive changes, so it's worth thinking a little bit about what, if, and how you'd like to absorb the changes

 * API is now actually null-safe
 * Added some basic tests. 
 * So far so obvious. The rest is more my OCD.... Replaced custom linked list implementations with Dart's
 * Changed the library structure to follow Dart's best practices.
 * And most invasively and breakingly: changed the public API to be more user-friendly.

Please take a look and let me know what you think. If it's too much hassle for you, I'm also happy to maintain the fork.

**Comment by mohammedX6** [comment]
you did great job, you are free to do what you want, everything seems working for me.
Thanks 🙏

**Comment by mohammedX6** [comment]
Closed, The library is now null safety thanks to all contributors.
